# **Web_Scraping_BeautifulSoup_CarDealer**

**PART 1**: https://www.youtube.com/watch?v=NkFc1nWGBg0

**PART 2**: https://www.youtube.com/watch?v=NCoQNa2AgkY&t=292s

**GITHUB**: https://github.com/LX-schlee/Web_Scraping_BeautifulSoup_CarDealer/blob/master/BS4_Car_Dealer_Final_Template.ipynb

**URL**: https://www.cars.com/shopping/results/?stock_type=cpo&makes%5B%5D=mercedes_benz&models%5B%5D&list_price_max&maximum_distance=all&zip

**Imports**

In [1]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

# HTTP Request
**store website in variable**

In [2]:
website = 'https://www.cars.com/shopping/results/?stock_type=cpo&makes%5B%5D=mercedes_benz&models%5B%5D=&list_price_max=&maximum_distance=20&zip='

**Get Request**

In [3]:
response = requests.get(website)

**Status Code**

In [4]:
response.status_code

200

**Soup Object**

In [5]:
soup = BeautifulSoup(response.content, 'html.parser')

**Results**

In [6]:
results = soup.find_all('div', {'class' : 'vehicle-card'})

In [7]:
len(results)

21

**Target necessary data**

In [ ]:
# Name
# Mileage
# Dealer Name
# Rating
# Rating Count
# Price

Name

In [8]:
results[0].find('h2').get_text()

'2021 Mercedes-Benz AMG A 35 Base'

Mileage

In [9]:
results[0].find('div', {'class':'mileage'}).get_text()

'14,733 mi.'

Dealer Name

In [10]:
results[0].find('div', {'class':'dealer-name'}).get_text().strip()

'Mercedes-Benz of South Charlotte'

Rating

In [11]:
results[0].find('span', {'class':'sds-rating__count'}).get_text()

'4.8'

Review Count

In [12]:
results[0].find('span', {'class':'sds-rating__link'}).get_text()

'(1,341 reviews)'

Price

In [13]:
results[0].find('span', {'class':'primary-price'}).get_text()

'$46,996'

# **Put everything together inside a For-Loop**

In [14]:
name = []
mileage = []
dealer_name = []
rating = []
review_count = []
price = []

for result in results:

    # name
    try:
        name.append(result.find('h2').get_text())
    except:
        name.append('n/a')

    # mileage
    try:
        mileage.append(result.find('div', {'class':'mileage'}).get_text())
    except:
        mileage.append('n/a')

    # dealer_name
    try:
        dealer_name.append(result.find('div', {'class':'dealer-name'}).get_text().strip())
    except:
        dealer_name.append('n/a')

    # rating
    try:
        rating.append(result.find('span', {'class':'sds-rating__count'}).get_text())
    except:
        rating.append('n/a')

    # review_count
    try:
        review_count.append(result.find('span', {'class':'sds-rating__link'}).get_text())
    except:
        review_count.append('n/a')

    #price
    try:
        price.append(result.find('span', {'class':'primary-price'}).get_text())
    except:
        price.append('n/a')

**Create Pandas Dataframe**

In [15]:
# dictionary
car_dealer = pd.DataFrame({'Name': name, 'Mileage':mileage, 'Dealer Name':dealer_name,
                                'Rating': rating, 'Review Count': review_count, 'Price': price})

In [16]:
car_dealer

,Name,Mileage,Dealer Name,Rating,Review Count,Price
0,2021 Mercedes-Benz AMG A 35 Base,"14,733 mi.",Mercedes-Benz of South Charlotte,4.8,"(1,341 reviews)","$46,996"
1,2020 Mercedes-Benz GLS 450 Base 4MATIC,"30,739 mi.",Mercedes-Benz of Springfield,4.9,(102 reviews),"$58,899"
2,2022 Mercedes-Benz AMG GLB 35 Base,"13,007 mi.",Mercedes-Benz of Springfield,4.9,(102 reviews),"$47,395"
3,2022 Mercedes-Benz AMG GLB 35 Base,"22,815 mi.",Mercedes-Benz of Chantilly,4.7,(978 reviews),"$47,600"
4,2019 Mercedes-Benz AMG E 53 Base 4MATIC,"23,163 mi.",Mercedes-Benz of State College,n/a,(2 reviews),"$59,491"
5,2023 Mercedes-Benz GLC 300 4MATIC Coupe,"3,731 mi.",Mercedes-Benz of Naperville,4.7,(928 reviews),"$57,977"
6,2021 Mercedes-Benz G-Class G 550 4MATIC,"15,981 mi.",Volkswagen of Quad Cities,4.9,(179 reviews),"$139,500"
7,2017 Mercedes-Benz C-Class C 300,"67,802 mi.",Mercedes-Benz of West Houston,4.7,(73 reviews),"$21,886"
8,2022 Mercedes-Benz AMG G 63 4MATIC,"8,095 mi.",Benzel-Busch Motor Car,4.5,"(5,344 reviews)","$199,902"
9,2021 Mercedes-Benz AMG C 43 Base 4MATIC,"30,903 mi.",Mercedes-Benz of Edison,5.0,"(4,069 reviews)","$50,995"
10,2021 Mercedes-Benz AMG C 43 Base 4MATIC,"18,182 mi.",Mercedes-Benz of Edison,5.0,"(4,069 reviews)","$58,999"
11,2020 Mercedes-Benz E-Class E 350 4MATIC,"34,977 mi.",Rallye Motors,4.8,"(4,246 reviews)","$39,900"
12,2021 Mercedes-Benz C-Class C 300 4MATIC,"40,614 mi.",Benzel-Busch Motor Car,4.5,"(5,344 reviews)","$50,987"
13,2023 Mercedes-Benz E-Class E 450,"1,537 mi.",Mercedes-Benz of Georgetown,4.6,(507 reviews),"$71,968"
14,2020 Mercedes-Benz AMG GLC 43,"40,981 mi.",Mercedes-Benz of Natick,4.9,"(2,567 reviews)","$45,998"
15,2019 Mercedes-Benz GLC 300 Base 4MATIC,"26,734 mi.",Sullivan-Parkhill,4.5,(436 reviews),"$33,545"
16,2016 Mercedes-Benz G-Class G 550,"66,617 mi.",Mercedes-Benz of Fort Wayne,n/a,(50 reviews),"$69,991"
17,2020 Mercedes-Benz SLC 300 Base,"11,411 mi.",Mercedes-Benz of North Olmsted,4.7,"(1,530 reviews)","$43,653"
18,2022 Mercedes-Benz GLC 300 Base 4MATIC,"6,116 mi.",Mercedes-Benz of Fort Mitchell,4.8,(633 reviews),"$39,845"
19,2020 Mercedes-Benz AMG GT 53 Base,"32,619 mi.",Mercedes-Benz of Pompano,4.5,(799 reviews),"$75,395"
20,2022 Mercedes-Benz GLE 450 4MATIC,"34,433 mi.",Mercedes-Benz of Chantilly,4.7,(978 reviews),"$67,100"

Data Cleaning

In [17]:
car_dealer['Review Count'] = car_dealer['Review Count'].apply(lambda x: x.strip('reviews)').strip('('))

In [18]:
# dataframe updated
car_dealer

,Name,Mileage,Dealer Name,Rating,Review Count,Price
0,2021 Mercedes-Benz AMG A 35 Base,"14,733 mi.",Mercedes-Benz of South Charlotte,4.8,"1,341","$46,996"
1,2020 Mercedes-Benz GLS 450 Base 4MATIC,"30,739 mi.",Mercedes-Benz of Springfield,4.9,102,"$58,899"
2,2022 Mercedes-Benz AMG GLB 35 Base,"13,007 mi.",Mercedes-Benz of Springfield,4.9,102,"$47,395"
3,2022 Mercedes-Benz AMG GLB 35 Base,"22,815 mi.",Mercedes-Benz of Chantilly,4.7,978,"$47,600"
4,2019 Mercedes-Benz AMG E 53 Base 4MATIC,"23,163 mi.",Mercedes-Benz of State College,n/a,2,"$59,491"
5,2023 Mercedes-Benz GLC 300 4MATIC Coupe,"3,731 mi.",Mercedes-Benz of Naperville,4.7,928,"$57,977"
6,2021 Mercedes-Benz G-Class G 550 4MATIC,"15,981 mi.",Volkswagen of Quad Cities,4.9,179,"$139,500"
7,2017 Mercedes-Benz C-Class C 300,"67,802 mi.",Mercedes-Benz of West Houston,4.7,73,"$21,886"
8,2022 Mercedes-Benz AMG G 63 4MATIC,"8,095 mi.",Benzel-Busch Motor Car,4.5,"5,344","$199,902"
9,2021 Mercedes-Benz AMG C 43 Base 4MATIC,"30,903 mi.",Mercedes-Benz of Edison,5.0,"4,069","$50,995"
10,2021 Mercedes-Benz AMG C 43 Base 4MATIC,"18,182 mi.",Mercedes-Benz of Edison,5.0,"4,069","$58,999"
11,2020 Mercedes-Benz E-Class E 350 4MATIC,"34,977 mi.",Rallye Motors,4.8,"4,246","$39,900"
12,2021 Mercedes-Benz C-Class C 300 4MATIC,"40,614 mi.",Benzel-Busch Motor Car,4.5,"5,344","$50,987"
13,2023 Mercedes-Benz E-Class E 450,"1,537 mi.",Mercedes-Benz of Georgetown,4.6,507,"$71,968"
14,2020 Mercedes-Benz AMG GLC 43,"40,981 mi.",Mercedes-Benz of Natick,4.9,"2,567","$45,998"
15,2019 Mercedes-Benz GLC 300 Base 4MATIC,"26,734 mi.",Sullivan-Parkhill,4.5,436,"$33,545"
16,2016 Mercedes-Benz G-Class G 550,"66,617 mi.",Mercedes-Benz of Fort Wayne,n/a,50,"$69,991"
17,2020 Mercedes-Benz SLC 300 Base,"11,411 mi.",Mercedes-Benz of North Olmsted,4.7,"1,530","$43,653"
18,2022 Mercedes-Benz GLC 300 Base 4MATIC,"6,116 mi.",Mercedes-Benz of Fort Mitchell,4.8,633,"$39,845"
19,2020 Mercedes-Benz AMG GT 53 Base,"32,619 mi.",Mercedes-Benz of Pompano,4.5,799,"$75,395"
20,2022 Mercedes-Benz GLE 450 4MATIC,"34,433 mi.",Mercedes-Benz of Chantilly,4.7,978,"$67,100"

**Output in Excel**

In [19]:
car_dealer.to_excel('car_dealer_single_page.xlsx', index=False)

# **Part 2 - Pagination**

In [20]:
name = []
mileage = []
dealer_name = []
rating = []
review_count = []
price = []

for i in range (1,11):

    # website in variable
    website = 'https://www.cars.com/shopping/results/?page='+ str(i) +'&page_size=20&dealer_id=&list_price_max=&list_price_min=&makes[]=mercedes_benz&maximum_distance=20&mileage_max=&sort=best_match_desc&stock_type=cpo&year_max=&year_min=&zip='

    # request to website
    response = requests.get(website)

    # soup object
    soup = BeautifulSoup(response.content, 'html.parser')

    # results
    results = soup.find_all('div', {'class' : 'vehicle-card'})

    # loop through results
    for result in results:

        # name
        try:
            name.append(result.find('h2').get_text())
        except:
            name.append('n/a')

        # mileage
        try:
            mileage.append(result.find('div', {'class':'mileage'}).get_text())
        except:
            mileage.append('n/a')

        # dealer_name
        try:
            dealer_name.append(result.find('div', {'class':'dealer-name'}).get_text().strip())
        except:
            dealer_name.append('n/a')

        # rating
        try:
            rating.append(result.find('span', {'class':'sds-rating__count'}).get_text())
        except:
            rating.append('n/a')

        # review_count
        try:
            review_count.append(result.find('span', {'class':'sds-rating__link'}).get_text())
        except:
            review_count.append('n/a')

        #price
        try:
            price.append(result.find('span', {'class':'primary-price'}).get_text())
        except:
            price.append('n/a')

In [21]:
# dictionary
car_dealer = pd.DataFrame({'Name': name, 'Mileage':mileage, 'Dealer Name':dealer_name,
                                'Rating': rating, 'Review Count': review_count, 'Price': price})

In [25]:
car_dealer

,Name,Mileage,Dealer Name,Rating,Review Count,Price
0,2022 Mercedes-Benz AMG GLC 43 Base 4MATIC,"5,047 mi.",Mercedes-Benz of Kansas City,4.7,777,"$67,894"
1,2020 Mercedes-Benz GLS 450 Base 4MATIC,"30,739 mi.",Mercedes-Benz of Springfield,4.9,102,"$58,899"
2,2022 Mercedes-Benz AMG GLB 35 Base,"13,007 mi.",Mercedes-Benz of Springfield,4.9,102,"$47,395"
3,2022 Mercedes-Benz AMG GLB 35 Base,"22,815 mi.",Mercedes-Benz of Chantilly,4.7,978,"$47,600"
4,2019 Mercedes-Benz AMG E 53 Base 4MATIC,"23,163 mi.",Mercedes-Benz of State College,n/a,2,"$59,491"
...,...,...,...,...,...,...
205,2022 Mercedes-Benz AMG GT 53 Base,"5,138 mi.",Mercedes-Benz of White Plains,4.3,"1,645","$109,000"
206,2019 Mercedes-Benz S-Class S 450,"32,088 mi.",Mercedes-Benz of Melbourne,n/a,177,"$54,215"
207,2022 Mercedes-Benz E-Class E 350,"14,742 mi.",Mercedes-Benz of Melbourne,n/a,177,"$49,700"
208,2020 Mercedes-Benz E-Class E 350 4MATIC,"38,608 mi.",Mercedes-Benz of Easton,4.6,684,"$41,453"
209,2022 Mercedes-Benz AMG GLB 35 Base,"13,310 mi.",Mercedes-Benz of Modesto,n/a,142,"$49,955"

In [23]:
car_dealer['Review Count'] = car_dealer['Review Count'].apply(lambda x: x.strip('reviews)').strip('('))

In [24]:
car_dealer

,Name,Mileage,Dealer Name,Rating,Review Count,Price
0,2022 Mercedes-Benz AMG GLC 43 Base 4MATIC,"5,047 mi.",Mercedes-Benz of Kansas City,4.7,777,"$67,894"
1,2020 Mercedes-Benz GLS 450 Base 4MATIC,"30,739 mi.",Mercedes-Benz of Springfield,4.9,102,"$58,899"
2,2022 Mercedes-Benz AMG GLB 35 Base,"13,007 mi.",Mercedes-Benz of Springfield,4.9,102,"$47,395"
3,2022 Mercedes-Benz AMG GLB 35 Base,"22,815 mi.",Mercedes-Benz of Chantilly,4.7,978,"$47,600"
4,2019 Mercedes-Benz AMG E 53 Base 4MATIC,"23,163 mi.",Mercedes-Benz of State College,n/a,2,"$59,491"
...,...,...,...,...,...,...
205,2022 Mercedes-Benz AMG GT 53 Base,"5,138 mi.",Mercedes-Benz of White Plains,4.3,"1,645","$109,000"
206,2019 Mercedes-Benz S-Class S 450,"32,088 mi.",Mercedes-Benz of Melbourne,n/a,177,"$54,215"
207,2022 Mercedes-Benz E-Class E 350,"14,742 mi.",Mercedes-Benz of Melbourne,n/a,177,"$49,700"
208,2020 Mercedes-Benz E-Class E 350 4MATIC,"38,608 mi.",Mercedes-Benz of Easton,4.6,684,"$41,453"
209,2022 Mercedes-Benz AMG GLB 35 Base,"13,310 mi.",Mercedes-Benz of Modesto,n/a,142,"$49,955"

In [26]:
car_dealer.to_excel('car_dealer_multi_page.xlsx', index=False)

end of the project: as on 26th july 2023